- name: Load Schema 
  hosts: all
  become: yes 
  tasks:    
    - name: Install MySQL Client Packages 
      yum: 
        name: "{{item}}"
        state: latest 
      loop:
        - MySQL-python
        - mariadb 

    - name: Load Schema 
      mysql_db:
        login_host: "{{DBHOST}}"
        login_user: "{{DBUSER}}"
        login_password: "{{DBPASS}}"
        state: import
        name: all
        target: /tmp/schema.sql

