- name: Install Web Server
  hosts: all
  become: yes
  roles:
    - webserver
    - appserver

- name: Load Schema 
      mysql_db:
        login_host: "{{DBHOST}}"
        login_user: "{{DBUSER}}"
        login_password: "{{DBPASS}}"
        state: import
        name: all
        target: /tmp/schema.sql


    
