- name: Install Web Server
  hosts: all
  become: yes
  vars:
    HTDOCS_DIR: /usr/share/nginx/html/
  tasks: 
    - name: Install Nginx server
      yum: 
        name: nginx
        state: present

    - name: find files in htdocs
      find:
        paths: "{{HTDOCS_DIR}}"
        file_type: any
      register: out
    
    - name: Remove all nginx default htdoc
      file: 
        path: "{{item.path}}"
        state: absent
      loop: "{{out.files}}" 
