- name: Add application user
  user:
    name: "{{App_User}}"
    comment: "Student project application user"

- name: Install Java
  yum:
    name: java
    state: installed

- name: Print ID
  shell: id
  register: out
  become_user: "{{App_User}}"
  
- name: Printing the ID value
  debug:
    msg: "ID = {{out.stdout}}"