- name: Loop a task
  hosts: all
  tasks:
    - name: Print loop values
      debug:
        msg: "Course Name = {{item.Course_name}} and Trainer Name = {{item.Trainer_name}}"
      loop:
        - { Course_name : "Devops" , Trainer_name : "Vamsi"}
        - { Course_name : "AWS" , Trainer_name : "Samalya"}