- name: Copy a config file
  hosts: all
  tasks:
    - name: install nginx server
      yum:
        name: nginx
        state: installed

    - name: Copy afile
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Restart nginx
      service:
        name: nginx
        state: restarted