- name: Copy a config file with template
  hosts: all
  become: yes
  tasks:
    - name: Install web server
      yum:
        name: nginx
        state: installed

    - name: Copy a template file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      vars:
        URL: google.com

    - name: Restart nginx
      service:
        name: nginx
        state: restarted