- name: Vars
  hosts: all
  vars:
    URL:  Vars.google.com
  tasks: 
    - name: Access Variable
      debug:
        msg: "Hello from {{URL}}"

- name: Demo on vars from localhost
  hosts: localhost
  vars: 
    URL: Vras.Devops/Raghu.com
  tasks:
    - name: Access Variable
      debug:
        msg: "Hello from {{URL}}"

- name: Demo on vars from prompt
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  tasks: 
    - name: Access Variable
      debug:
        msg: "URL == {{URL}}"

- name: Demo on Var files
  hosts: localhost
  vars_files:
    - var01.yml
   tasks: 
    - name: Access Variable
      debug:
        msg: "URL == {{URL}}" 

        

